#!/bin/sh
#
# cblogger - this script starts and stops the cblogger daemon
#
# chkconfig:   - 85 15
# description:  cblogger logs callbacks from adjust to a csv
# processname: cblogger
# pidfile:     /var/run/cblogger.pid

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ "$NETWORKING" = "no" ] && exit 0

cblogger="/usr/local/bin/cblogger"
prog=$(basename $cblogger)

sysconfig="/etc/sysconfig/$prog"
lockfile="/var/lock/subsys/$prog"
pidfile="/var/run/${prog}.pid"
logfile="/var/log/cblogger"
csvdir='/var/log/'
csvfile='csv'

[ -f $sysconfig ] && . $sysconfig

start() {
    [ -x $cblogger ] || exit 5
    echo -n $"Starting $prog: "
    daemon daemonize -a -p $pidfile -l $lockfile -o $logfile -e $logfile $cblogger --logdir $csvdir --logfile $csvfile --port 80
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    echo $pidfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc -p $pidfile $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

rh_status() {
    status $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}

case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    status)
        rh_$1
        ;;
    restart)
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|reload|status|restart}"
        exit 2
esac

